<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/src',
        __DIR__ . '/tests',
        __DIR__ . '/.php-cs-fixer.dist.php',
        __FILE__,
    ])
    // src/Thrift is generated by bin/thrift-gen.sh and must stay byte-for-byte reproducible from
    // the IDL, so its shape is the thrift compiler's contract rather than ours.
    ->withSkip([
        __DIR__ . '/src/Thrift',
    ])
    ->withPhpSets(php84: true)
    ->withPreparedSets(
        deadCode: true,
        codeQuality: true,
        codingStyle: true,
        typeDeclarations: true,
        privatization: true,
        earlyReturn: true,
    )
    ->withImportNames(removeUnusedImports: true);
