<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent\Zipkin;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * An annotation is similar to a log statement. It includes a host field which
 * allows these events to be attributed properly, and also aggregatable.
 */
class Annotation
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'timestamp',
            'isRequired' => false,
            'type' => TType::I64,
        ],
        2 => [
            'var' => 'value',
            'isRequired' => false,
            'type' => TType::STRING,
        ],
        3 => [
            'var' => 'host',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Jaeger\Thrift\Agent\Zipkin\Endpoint',
        ],
    ];

    /**
     * Microseconds from epoch.
     *
     * This value should use the most precise value possible. For example,
     * gettimeofday or syncing nanoTime against a tick of currentTimeMillis.
     *
     */
    public ?int $timestamp = null;
    public ?string $value = null;
    /**
     * Always the host that recorded the event. By specifying the host you allow
     * rollup of all events (such as client requests to a service) by IP address.
     *
     */
    public ?Endpoint $host = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['timestamp'])) {
                $this->timestamp = (int)$vals['timestamp'];
            }
            if (isset($vals['value'])) {
                $this->value = (string)$vals['value'];
            }
            if (isset($vals['host'])) {
                $this->host = $vals['host'];
            }
        }
    }

    public function getName(): string
    {
        return 'Annotation';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::I64) {
                            $xfer += $input->readI64($this->timestamp);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 2:
                        if ($ftype == TType::STRING) {
                            $xfer += $input->readString($this->value);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 3:
                        if ($ftype == TType::STRUCT) {
                            $this->host = new \Jaeger\Thrift\Agent\Zipkin\Endpoint();
                            $xfer += $this->host->read($input);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('Annotation');
            if ($this->timestamp !== null) {
                $xfer += $output->writeFieldBegin('timestamp', TType::I64, 1);
                $xfer += $output->writeI64($this->timestamp);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->value !== null) {
                $xfer += $output->writeFieldBegin('value', TType::STRING, 2);
                $xfer += $output->writeString($this->value);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->host !== null) {
                if (!is_object($this->host)) {
                    throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
                }
                $xfer += $output->writeFieldBegin('host', TType::STRUCT, 3);
                $xfer += $this->host->write($output);
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
