<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent\Zipkin;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class AnnotationType
{
    public const BOOL = 0;

    public const BYTES = 1;

    public const I16 = 2;

    public const I32 = 3;

    public const I64 = 4;

    public const DOUBLE = 5;

    public const STRING = 6;

    public static $names = [
        0 => 'BOOL',
        1 => 'BYTES',
        2 => 'I16',
        3 => 'I32',
        4 => 'I64',
        5 => 'DOUBLE',
        6 => 'STRING',
    ];
}
