<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent\Zipkin;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Binary annotations are tags applied to a Span to give it context. For
 * example, a binary annotation of "http.uri" could the path to a resource in a
 * RPC call.
 *
 * Binary annotations of type STRING are always queryable, though more a
 * historical implementation detail than a structural concern.
 *
 * Binary annotations can repeat, and vary on the host. Similar to Annotation,
 * the host indicates who logged the event. This allows you to tell the
 * difference between the client and server side of the same key. For example,
 * the key "http.uri" might be different on the client and server side due to
 * rewriting, like "/api/v1/myresource" vs "/myresource. Via the host field,
 * you can see the different points of view, which often help in debugging.
 */
class BinaryAnnotation
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'key',
            'isRequired' => false,
            'type' => TType::STRING,
        ],
        2 => [
            'var' => 'value',
            'isRequired' => false,
            'type' => TType::STRING,
        ],
        3 => [
            'var' => 'annotation_type',
            'isRequired' => false,
            'type' => TType::I32,
            'class' => '\Jaeger\Thrift\Agent\Zipkin\AnnotationType',
        ],
        4 => [
            'var' => 'host',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Jaeger\Thrift\Agent\Zipkin\Endpoint',
        ],
    ];

    public ?string $key = null;
    public ?string $value = null;
    public ?int $annotation_type = null;
    /**
     * The host that recorded tag, which allows you to differentiate between
     * multiple tags with the same key. There are two exceptions to this.
     *
     * When the key is CLIENT_ADDR or SERVER_ADDR, host indicates the source or
     * destination of an RPC. This exception allows zipkin to display network
     * context of uninstrumented services, or clients such as web browsers.
     *
     */
    public ?Endpoint $host = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['key'])) {
                $this->key = (string)$vals['key'];
            }
            if (isset($vals['value'])) {
                $this->value = (string)$vals['value'];
            }
            if (isset($vals['annotation_type'])) {
                $this->annotation_type = (int)$vals['annotation_type'];
            }
            if (isset($vals['host'])) {
                $this->host = $vals['host'];
            }
        }
    }

    public function getName(): string
    {
        return 'BinaryAnnotation';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::STRING) {
                            $xfer += $input->readString($this->key);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 2:
                        if ($ftype == TType::STRING) {
                            $xfer += $input->readString($this->value);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 3:
                        if ($ftype == TType::I32) {
                            $xfer += $input->readI32($this->annotation_type);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 4:
                        if ($ftype == TType::STRUCT) {
                            $this->host = new \Jaeger\Thrift\Agent\Zipkin\Endpoint();
                            $xfer += $this->host->read($input);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('BinaryAnnotation');
            if ($this->key !== null) {
                $xfer += $output->writeFieldBegin('key', TType::STRING, 1);
                $xfer += $output->writeString($this->key);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->value !== null) {
                $xfer += $output->writeFieldBegin('value', TType::STRING, 2);
                $xfer += $output->writeString($this->value);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->annotation_type !== null) {
                $xfer += $output->writeFieldBegin('annotation_type', TType::I32, 3);
                $xfer += $output->writeI32($this->annotation_type);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->host !== null) {
                if (!is_object($this->host)) {
                    throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
                }
                $xfer += $output->writeFieldBegin('host', TType::STRUCT, 4);
                $xfer += $this->host->write($output);
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
