<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent\Zipkin;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Response
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'ok',
            'isRequired' => true,
            'type' => TType::BOOL,
        ],
    ];

    public ?bool $ok = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['ok'])) {
                $this->ok = (bool)$vals['ok'];
            }
        }
    }

    public function getName(): string
    {
        return 'Response';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::BOOL) {
                            $xfer += $input->readBool($this->ok);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('Response');
            if ($this->ok !== null) {
                $xfer += $output->writeFieldBegin('ok', TType::BOOL, 1);
                $xfer += $output->writeBool($this->ok);
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
