<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 *
 * phpcs:disable Squiz.Classes.ValidClassName
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent\Zipkin;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ZipkinCollector_submitZipkinBatch_args
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'spans',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => [
                'type' => TType::STRUCT,
                'class' => '\Jaeger\Thrift\Agent\Zipkin\Span',
            ],
        ],
    ];

    /**
     * @var \Jaeger\Thrift\Agent\Zipkin\Span[]
     */
    public ?array $spans = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['spans'])) {
                $this->spans = $vals['spans'];
            }
        }
    }

    public function getName(): string
    {
        return 'ZipkinCollector_submitZipkinBatch_args';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::LST) {
                            $this->spans = [];
                            $_size14 = 0;
                            $_etype17 = 0;
                            $xfer += $input->readListBegin($_etype17, $_size14);
                            for ($_i18 = 0; $_i18 < $_size14; ++$_i18) {
                                $elem19 = null;
                                $elem19 = new \Jaeger\Thrift\Agent\Zipkin\Span();
                                $xfer += $elem19->read($input);
                                $this->spans[] = $elem19;
                            }
                            $xfer += $input->readListEnd();
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('ZipkinCollector_submitZipkinBatch_args');
            if ($this->spans !== null) {
                if (!is_array($this->spans)) {
                    throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
                }
                $xfer += $output->writeFieldBegin('spans', TType::LST, 1);
                $output->writeListBegin(TType::STRUCT, count($this->spans));
                foreach ($this->spans as $iter20) {
                    $xfer += $iter20->write($output);
                }
                $output->writeListEnd();
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
