<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 *
 * phpcs:disable PSR1.Methods.CamelCapsMethodName
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent\Zipkin;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ZipkinCollectorClient implements \Jaeger\Thrift\Agent\Zipkin\ZipkinCollectorIf
{
    protected ?TProtocol $input = null;
    protected ?TProtocol $output = null;

    protected int $seqid = 0;

    public function __construct(TProtocol $input, ?TProtocol $output = null)
    {
        $this->input = $input;
        $this->output = $output ? $output : $input;
    }


    public function submitZipkinBatch(?array $spans): ?array
    {
        $this->send_submitZipkinBatch($spans);
        return $this->recv_submitZipkinBatch();
    }

    public function send_submitZipkinBatch(?array $spans): void
    {
        $args = new \Jaeger\Thrift\Agent\Zipkin\ZipkinCollector_submitZipkinBatch_args();
        $args->spans = $spans;
        $bin_accel = ($this->output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
        if ($bin_accel) {
            thrift_protocol_write_binary(
                $this->output,
                'submitZipkinBatch',
                TMessageType::CALL,
                $args,
                $this->seqid,
                $this->output->isStrictWrite()
            );
        } else {
            $this->output->writeMessageBegin('submitZipkinBatch', TMessageType::CALL, $this->seqid);
            $args->write($this->output);
            $this->output->writeMessageEnd();
            $this->output->getTransport()->flush();
        }
    }

    public function recv_submitZipkinBatch(): ?array
    {
        $bin_accel = ($this->input instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
        if ($bin_accel) {
            $result = thrift_protocol_read_binary(
                $this->input,
                '\Jaeger\Thrift\Agent\Zipkin\ZipkinCollector_submitZipkinBatch_result',
                $this->input->isStrictRead()
            );
        } else {
            $rseqid = 0;
            $fname = null;
            $mtype = 0;

            $this->input->readMessageBegin($fname, $mtype, $rseqid);
            if ($mtype == TMessageType::EXCEPTION) {
                $x = new TApplicationException();
                $x->read($this->input);
                $this->input->readMessageEnd();
                throw $x;
            }
            $result = new \Jaeger\Thrift\Agent\Zipkin\ZipkinCollector_submitZipkinBatch_result();
            $result->read($this->input);
            $this->input->readMessageEnd();
        }
        if ($result->success !== null) {
            return $result->success;
        }
        throw new \Exception("submitZipkinBatch failed: unknown result");
    }
}
