<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ClientStats
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'fullQueueDroppedSpans',
            'isRequired' => true,
            'type' => TType::I64,
        ],
        2 => [
            'var' => 'tooLargeDroppedSpans',
            'isRequired' => true,
            'type' => TType::I64,
        ],
        3 => [
            'var' => 'failedToEmitSpans',
            'isRequired' => true,
            'type' => TType::I64,
        ],
    ];

    public ?int $fullQueueDroppedSpans = null;
    public ?int $tooLargeDroppedSpans = null;
    public ?int $failedToEmitSpans = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['fullQueueDroppedSpans'])) {
                $this->fullQueueDroppedSpans = (int)$vals['fullQueueDroppedSpans'];
            }
            if (isset($vals['tooLargeDroppedSpans'])) {
                $this->tooLargeDroppedSpans = (int)$vals['tooLargeDroppedSpans'];
            }
            if (isset($vals['failedToEmitSpans'])) {
                $this->failedToEmitSpans = (int)$vals['failedToEmitSpans'];
            }
        }
    }

    public function getName(): string
    {
        return 'ClientStats';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::I64) {
                            $xfer += $input->readI64($this->fullQueueDroppedSpans);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 2:
                        if ($ftype == TType::I64) {
                            $xfer += $input->readI64($this->tooLargeDroppedSpans);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 3:
                        if ($ftype == TType::I64) {
                            $xfer += $input->readI64($this->failedToEmitSpans);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('ClientStats');
            if ($this->fullQueueDroppedSpans !== null) {
                $xfer += $output->writeFieldBegin('fullQueueDroppedSpans', TType::I64, 1);
                $xfer += $output->writeI64($this->fullQueueDroppedSpans);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->tooLargeDroppedSpans !== null) {
                $xfer += $output->writeFieldBegin('tooLargeDroppedSpans', TType::I64, 2);
                $xfer += $output->writeI64($this->tooLargeDroppedSpans);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->failedToEmitSpans !== null) {
                $xfer += $output->writeFieldBegin('failedToEmitSpans', TType::I64, 3);
                $xfer += $output->writeI64($this->failedToEmitSpans);
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
