<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 *
 * phpcs:disable Squiz.Classes.ValidClassName
 */

declare(strict_types=1);

namespace Jaeger\Thrift;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Collector_submitBatches_args
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'batches',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => [
                'type' => TType::STRUCT,
                'class' => '\Jaeger\Thrift\Batch',
            ],
        ],
    ];

    /**
     * @var \Jaeger\Thrift\Batch[]
     */
    public ?array $batches = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['batches'])) {
                $this->batches = $vals['batches'];
            }
        }
    }

    public function getName(): string
    {
        return 'Collector_submitBatches_args';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::LST) {
                            $this->batches = [];
                            $_size42 = 0;
                            $_etype45 = 0;
                            $xfer += $input->readListBegin($_etype45, $_size42);
                            for ($_i46 = 0; $_i46 < $_size42; ++$_i46) {
                                $elem47 = null;
                                $elem47 = new \Jaeger\Thrift\Batch();
                                $xfer += $elem47->read($input);
                                $this->batches[] = $elem47;
                            }
                            $xfer += $input->readListEnd();
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('Collector_submitBatches_args');
            if ($this->batches !== null) {
                if (!is_array($this->batches)) {
                    throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
                }
                $xfer += $output->writeFieldBegin('batches', TType::LST, 1);
                $output->writeListBegin(TType::STRUCT, count($this->batches));
                foreach ($this->batches as $iter48) {
                    $xfer += $iter48->write($output);
                }
                $output->writeListEnd();
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
