<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Process
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'serviceName',
            'isRequired' => true,
            'type' => TType::STRING,
        ],
        2 => [
            'var' => 'tags',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => [
                'type' => TType::STRUCT,
                'class' => '\Jaeger\Thrift\Tag',
            ],
        ],
    ];

    public ?string $serviceName = null;
    /**
     * @var \Jaeger\Thrift\Tag[]
     */
    public ?array $tags = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['serviceName'])) {
                $this->serviceName = (string)$vals['serviceName'];
            }
            if (isset($vals['tags'])) {
                $this->tags = $vals['tags'];
            }
        }
    }

    public function getName(): string
    {
        return 'Process';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::STRING) {
                            $xfer += $input->readString($this->serviceName);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 2:
                        if ($ftype == TType::LST) {
                            $this->tags = [];
                            $_size28 = 0;
                            $_etype31 = 0;
                            $xfer += $input->readListBegin($_etype31, $_size28);
                            for ($_i32 = 0; $_i32 < $_size28; ++$_i32) {
                                $elem33 = null;
                                $elem33 = new \Jaeger\Thrift\Tag();
                                $xfer += $elem33->read($input);
                                $this->tags[] = $elem33;
                            }
                            $xfer += $input->readListEnd();
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('Process');
            if ($this->serviceName !== null) {
                $xfer += $output->writeFieldBegin('serviceName', TType::STRING, 1);
                $xfer += $output->writeString($this->serviceName);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->tags !== null) {
                if (!is_array($this->tags)) {
                    throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
                }
                $xfer += $output->writeFieldBegin('tags', TType::LST, 2);
                $output->writeListBegin(TType::STRUCT, count($this->tags));
                foreach ($this->tags as $iter34) {
                    $xfer += $iter34->write($output);
                }
                $output->writeListEnd();
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
