<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class SpanRef
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'refType',
            'isRequired' => true,
            'type' => TType::I32,
            'class' => '\Jaeger\Thrift\SpanRefType',
        ],
        2 => [
            'var' => 'traceIdLow',
            'isRequired' => true,
            'type' => TType::I64,
        ],
        3 => [
            'var' => 'traceIdHigh',
            'isRequired' => true,
            'type' => TType::I64,
        ],
        4 => [
            'var' => 'spanId',
            'isRequired' => true,
            'type' => TType::I64,
        ],
    ];

    public ?int $refType = null;
    public ?int $traceIdLow = null;
    public ?int $traceIdHigh = null;
    public ?int $spanId = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['refType'])) {
                $this->refType = (int)$vals['refType'];
            }
            if (isset($vals['traceIdLow'])) {
                $this->traceIdLow = (int)$vals['traceIdLow'];
            }
            if (isset($vals['traceIdHigh'])) {
                $this->traceIdHigh = (int)$vals['traceIdHigh'];
            }
            if (isset($vals['spanId'])) {
                $this->spanId = (int)$vals['spanId'];
            }
        }
    }

    public function getName(): string
    {
        return 'SpanRef';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::I32) {
                            $xfer += $input->readI32($this->refType);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 2:
                        if ($ftype == TType::I64) {
                            $xfer += $input->readI64($this->traceIdLow);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 3:
                        if ($ftype == TType::I64) {
                            $xfer += $input->readI64($this->traceIdHigh);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 4:
                        if ($ftype == TType::I64) {
                            $xfer += $input->readI64($this->spanId);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('SpanRef');
            if ($this->refType !== null) {
                $xfer += $output->writeFieldBegin('refType', TType::I32, 1);
                $xfer += $output->writeI32($this->refType);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->traceIdLow !== null) {
                $xfer += $output->writeFieldBegin('traceIdLow', TType::I64, 2);
                $xfer += $output->writeI64($this->traceIdLow);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->traceIdHigh !== null) {
                $xfer += $output->writeFieldBegin('traceIdHigh', TType::I64, 3);
                $xfer += $output->writeI64($this->traceIdHigh);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->spanId !== null) {
                $xfer += $output->writeFieldBegin('spanId', TType::I64, 4);
                $xfer += $output->writeI64($this->spanId);
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
