<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Tag
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'key',
            'isRequired' => true,
            'type' => TType::STRING,
        ],
        2 => [
            'var' => 'vType',
            'isRequired' => true,
            'type' => TType::I32,
            'class' => '\Jaeger\Thrift\TagType',
        ],
        3 => [
            'var' => 'vStr',
            'isRequired' => false,
            'type' => TType::STRING,
        ],
        4 => [
            'var' => 'vDouble',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ],
        5 => [
            'var' => 'vBool',
            'isRequired' => false,
            'type' => TType::BOOL,
        ],
        6 => [
            'var' => 'vLong',
            'isRequired' => false,
            'type' => TType::I64,
        ],
        7 => [
            'var' => 'vBinary',
            'isRequired' => false,
            'type' => TType::STRING,
        ],
    ];

    public ?string $key = null;
    public ?int $vType = null;
    public ?string $vStr = null;
    public ?float $vDouble = null;
    public ?bool $vBool = null;
    public ?int $vLong = null;
    public ?string $vBinary = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['key'])) {
                $this->key = (string)$vals['key'];
            }
            if (isset($vals['vType'])) {
                $this->vType = (int)$vals['vType'];
            }
            if (isset($vals['vStr'])) {
                $this->vStr = (string)$vals['vStr'];
            }
            if (isset($vals['vDouble'])) {
                $this->vDouble = (float)$vals['vDouble'];
            }
            if (isset($vals['vBool'])) {
                $this->vBool = (bool)$vals['vBool'];
            }
            if (isset($vals['vLong'])) {
                $this->vLong = (int)$vals['vLong'];
            }
            if (isset($vals['vBinary'])) {
                $this->vBinary = (string)$vals['vBinary'];
            }
        }
    }

    public function getName(): string
    {
        return 'Tag';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::STRING) {
                            $xfer += $input->readString($this->key);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 2:
                        if ($ftype == TType::I32) {
                            $xfer += $input->readI32($this->vType);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 3:
                        if ($ftype == TType::STRING) {
                            $xfer += $input->readString($this->vStr);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 4:
                        if ($ftype == TType::DOUBLE) {
                            $xfer += $input->readDouble($this->vDouble);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 5:
                        if ($ftype == TType::BOOL) {
                            $xfer += $input->readBool($this->vBool);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 6:
                        if ($ftype == TType::I64) {
                            $xfer += $input->readI64($this->vLong);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 7:
                        if ($ftype == TType::STRING) {
                            $xfer += $input->readString($this->vBinary);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('Tag');
            if ($this->key !== null) {
                $xfer += $output->writeFieldBegin('key', TType::STRING, 1);
                $xfer += $output->writeString($this->key);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->vType !== null) {
                $xfer += $output->writeFieldBegin('vType', TType::I32, 2);
                $xfer += $output->writeI32($this->vType);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->vStr !== null) {
                $xfer += $output->writeFieldBegin('vStr', TType::STRING, 3);
                $xfer += $output->writeString($this->vStr);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->vDouble !== null) {
                $xfer += $output->writeFieldBegin('vDouble', TType::DOUBLE, 4);
                $xfer += $output->writeDouble($this->vDouble);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->vBool !== null) {
                $xfer += $output->writeFieldBegin('vBool', TType::BOOL, 5);
                $xfer += $output->writeBool($this->vBool);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->vLong !== null) {
                $xfer += $output->writeFieldBegin('vLong', TType::I64, 6);
                $xfer += $output->writeI64($this->vLong);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->vBinary !== null) {
                $xfer += $output->writeFieldBegin('vBinary', TType::STRING, 7);
                $xfer += $output->writeString($this->vBinary);
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
