<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class TagType
{
    public const STRING = 0;

    public const DOUBLE = 1;

    public const BOOL = 2;

    public const LONG = 3;

    public const BINARY = 4;

    public static $names = [
        0 => 'STRING',
        1 => 'DOUBLE',
        2 => 'BOOL',
        3 => 'LONG',
        4 => 'BINARY',
    ];
}
