<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface AgentIf
{
    /**
     * @param \Jaeger\Thrift\Agent\Zipkin\Span[] $spans
     */
    public function emitZipkinBatch(?array $spans): void;
    /**
     * @param \Jaeger\Thrift\Batch $batch
     */
    public function emitBatch(?\Jaeger\Thrift\Batch $batch): void;
}
