<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 *
 * phpcs:disable PSR1.Methods.CamelCapsMethodName
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class AgentClient implements \Jaeger\Thrift\Agent\AgentIf
{
    protected ?TProtocol $input = null;
    protected ?TProtocol $output = null;

    protected int $seqid = 0;

    public function __construct(TProtocol $input, ?TProtocol $output = null)
    {
        $this->input = $input;
        $this->output = $output ? $output : $input;
    }


    public function emitZipkinBatch(?array $spans): void
    {
        $this->send_emitZipkinBatch($spans);
    }

    public function send_emitZipkinBatch(?array $spans): void
    {
        $args = new \Jaeger\Thrift\Agent\Agent_emitZipkinBatch_args();
        $args->spans = $spans;
        $bin_accel = ($this->output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
        if ($bin_accel) {
            thrift_protocol_write_binary(
                $this->output,
                'emitZipkinBatch',
                TMessageType::ONEWAY,
                $args,
                $this->seqid,
                $this->output->isStrictWrite()
            );
        } else {
            $this->output->writeMessageBegin('emitZipkinBatch', TMessageType::ONEWAY, $this->seqid);
            $args->write($this->output);
            $this->output->writeMessageEnd();
            $this->output->getTransport()->flush();
        }
    }

    public function emitBatch(?\Jaeger\Thrift\Batch $batch): void
    {
        $this->send_emitBatch($batch);
    }

    public function send_emitBatch(?\Jaeger\Thrift\Batch $batch): void
    {
        $args = new \Jaeger\Thrift\Agent\Agent_emitBatch_args();
        $args->batch = $batch;
        $bin_accel = ($this->output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
        if ($bin_accel) {
            thrift_protocol_write_binary(
                $this->output,
                'emitBatch',
                TMessageType::ONEWAY,
                $args,
                $this->seqid,
                $this->output->isStrictWrite()
            );
        } else {
            $this->output->writeMessageBegin('emitBatch', TMessageType::ONEWAY, $this->seqid);
            $args->write($this->output);
            $this->output->writeMessageEnd();
            $this->output->getTransport()->flush();
        }
    }
}
