<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 *
 * phpcs:disable Squiz.Classes.ValidClassName
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Agent_emitBatch_args
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'batch',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Jaeger\Thrift\Batch',
        ],
    ];

    public ?\Jaeger\Thrift\Batch $batch = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['batch'])) {
                $this->batch = $vals['batch'];
            }
        }
    }

    public function getName(): string
    {
        return 'Agent_emitBatch_args';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::STRUCT) {
                            $this->batch = new \Jaeger\Thrift\Batch();
                            $xfer += $this->batch->read($input);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('Agent_emitBatch_args');
            if ($this->batch !== null) {
                if (!is_object($this->batch)) {
                    throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
                }
                $xfer += $output->writeFieldBegin('batch', TType::STRUCT, 1);
                $xfer += $this->batch->write($output);
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
