<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class OperationSamplingStrategy
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'operation',
            'isRequired' => true,
            'type' => TType::STRING,
        ],
        2 => [
            'var' => 'probabilisticSampling',
            'isRequired' => true,
            'type' => TType::STRUCT,
            'class' => '\Jaeger\Thrift\Agent\ProbabilisticSamplingStrategy',
        ],
    ];

    public ?string $operation = null;
    public ?ProbabilisticSamplingStrategy $probabilisticSampling = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['operation'])) {
                $this->operation = (string)$vals['operation'];
            }
            if (isset($vals['probabilisticSampling'])) {
                $this->probabilisticSampling = $vals['probabilisticSampling'];
            }
        }
    }

    public function getName(): string
    {
        return 'OperationSamplingStrategy';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::STRING) {
                            $xfer += $input->readString($this->operation);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 2:
                        if ($ftype == TType::STRUCT) {
                            $this->probabilisticSampling = new \Jaeger\Thrift\Agent\ProbabilisticSamplingStrategy();
                            $xfer += $this->probabilisticSampling->read($input);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('OperationSamplingStrategy');
            if ($this->operation !== null) {
                $xfer += $output->writeFieldBegin('operation', TType::STRING, 1);
                $xfer += $output->writeString($this->operation);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->probabilisticSampling !== null) {
                if (!is_object($this->probabilisticSampling)) {
                    throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
                }
                $xfer += $output->writeFieldBegin('probabilisticSampling', TType::STRUCT, 2);
                $xfer += $this->probabilisticSampling->write($output);
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
