<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class PerOperationSamplingStrategies
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'defaultSamplingProbability',
            'isRequired' => true,
            'type' => TType::DOUBLE,
        ],
        2 => [
            'var' => 'defaultLowerBoundTracesPerSecond',
            'isRequired' => true,
            'type' => TType::DOUBLE,
        ],
        3 => [
            'var' => 'perOperationStrategies',
            'isRequired' => true,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => [
                'type' => TType::STRUCT,
                'class' => '\Jaeger\Thrift\Agent\OperationSamplingStrategy',
            ],
        ],
        4 => [
            'var' => 'defaultUpperBoundTracesPerSecond',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ],
    ];

    public ?float $defaultSamplingProbability = null;
    public ?float $defaultLowerBoundTracesPerSecond = null;
    /**
     * @var \Jaeger\Thrift\Agent\OperationSamplingStrategy[]
     */
    public ?array $perOperationStrategies = null;
    public ?float $defaultUpperBoundTracesPerSecond = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['defaultSamplingProbability'])) {
                $this->defaultSamplingProbability = (float)$vals['defaultSamplingProbability'];
            }
            if (isset($vals['defaultLowerBoundTracesPerSecond'])) {
                $this->defaultLowerBoundTracesPerSecond = (float)$vals['defaultLowerBoundTracesPerSecond'];
            }
            if (isset($vals['perOperationStrategies'])) {
                $this->perOperationStrategies = $vals['perOperationStrategies'];
            }
            if (isset($vals['defaultUpperBoundTracesPerSecond'])) {
                $this->defaultUpperBoundTracesPerSecond = (float)$vals['defaultUpperBoundTracesPerSecond'];
            }
        }
    }

    public function getName(): string
    {
        return 'PerOperationSamplingStrategies';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::DOUBLE) {
                            $xfer += $input->readDouble($this->defaultSamplingProbability);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 2:
                        if ($ftype == TType::DOUBLE) {
                            $xfer += $input->readDouble($this->defaultLowerBoundTracesPerSecond);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 3:
                        if ($ftype == TType::LST) {
                            $this->perOperationStrategies = [];
                            $_size0 = 0;
                            $_etype3 = 0;
                            $xfer += $input->readListBegin($_etype3, $_size0);
                            for ($_i4 = 0; $_i4 < $_size0; ++$_i4) {
                                $elem5 = null;
                                $elem5 = new \Jaeger\Thrift\Agent\OperationSamplingStrategy();
                                $xfer += $elem5->read($input);
                                $this->perOperationStrategies[] = $elem5;
                            }
                            $xfer += $input->readListEnd();
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 4:
                        if ($ftype == TType::DOUBLE) {
                            $xfer += $input->readDouble($this->defaultUpperBoundTracesPerSecond);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('PerOperationSamplingStrategies');
            if ($this->defaultSamplingProbability !== null) {
                $xfer += $output->writeFieldBegin('defaultSamplingProbability', TType::DOUBLE, 1);
                $xfer += $output->writeDouble($this->defaultSamplingProbability);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->defaultLowerBoundTracesPerSecond !== null) {
                $xfer += $output->writeFieldBegin('defaultLowerBoundTracesPerSecond', TType::DOUBLE, 2);
                $xfer += $output->writeDouble($this->defaultLowerBoundTracesPerSecond);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->perOperationStrategies !== null) {
                if (!is_array($this->perOperationStrategies)) {
                    throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
                }
                $xfer += $output->writeFieldBegin('perOperationStrategies', TType::LST, 3);
                $output->writeListBegin(TType::STRUCT, count($this->perOperationStrategies));
                foreach ($this->perOperationStrategies as $iter6) {
                    $xfer += $iter6->write($output);
                }
                $output->writeListEnd();
                $xfer += $output->writeFieldEnd();
            }
            if ($this->defaultUpperBoundTracesPerSecond !== null) {
                $xfer += $output->writeFieldBegin('defaultUpperBoundTracesPerSecond', TType::DOUBLE, 4);
                $xfer += $output->writeDouble($this->defaultUpperBoundTracesPerSecond);
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
