<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class SamplingStrategyResponse
{
    public static bool $isValidate = false;

    public static array $tspec = [
        1 => [
            'var' => 'strategyType',
            'isRequired' => true,
            'type' => TType::I32,
            'class' => '\Jaeger\Thrift\Agent\SamplingStrategyType',
        ],
        2 => [
            'var' => 'probabilisticSampling',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Jaeger\Thrift\Agent\ProbabilisticSamplingStrategy',
        ],
        3 => [
            'var' => 'rateLimitingSampling',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Jaeger\Thrift\Agent\RateLimitingSamplingStrategy',
        ],
        4 => [
            'var' => 'operationSampling',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Jaeger\Thrift\Agent\PerOperationSamplingStrategies',
        ],
    ];

    public ?int $strategyType = null;
    public ?ProbabilisticSamplingStrategy $probabilisticSampling = null;
    public ?RateLimitingSamplingStrategy $rateLimitingSampling = null;
    public ?PerOperationSamplingStrategies $operationSampling = null;

    public function __construct(?array $vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['strategyType'])) {
                $this->strategyType = (int)$vals['strategyType'];
            }
            if (isset($vals['probabilisticSampling'])) {
                $this->probabilisticSampling = $vals['probabilisticSampling'];
            }
            if (isset($vals['rateLimitingSampling'])) {
                $this->rateLimitingSampling = $vals['rateLimitingSampling'];
            }
            if (isset($vals['operationSampling'])) {
                $this->operationSampling = $vals['operationSampling'];
            }
        }
    }

    public function getName(): string
    {
        return 'SamplingStrategyResponse';
    }

    public function read(TProtocol $input): int
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $input->incrementRecursionDepth();
        try {
            $xfer += $input->readStructBegin($fname);
            while (true) {
                $xfer += $input->readFieldBegin($fname, $ftype, $fid);
                if ($ftype == TType::STOP) {
                    break;
                }
                switch ($fid) {
                    case 1:
                        if ($ftype == TType::I32) {
                            $xfer += $input->readI32($this->strategyType);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 2:
                        if ($ftype == TType::STRUCT) {
                            $this->probabilisticSampling = new \Jaeger\Thrift\Agent\ProbabilisticSamplingStrategy();
                            $xfer += $this->probabilisticSampling->read($input);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 3:
                        if ($ftype == TType::STRUCT) {
                            $this->rateLimitingSampling = new \Jaeger\Thrift\Agent\RateLimitingSamplingStrategy();
                            $xfer += $this->rateLimitingSampling->read($input);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    case 4:
                        if ($ftype == TType::STRUCT) {
                            $this->operationSampling = new \Jaeger\Thrift\Agent\PerOperationSamplingStrategies();
                            $xfer += $this->operationSampling->read($input);
                        } else {
                            $xfer += $input->skip($ftype);
                        }
                        break;
                    default:
                        $xfer += $input->skip($ftype);
                        break;
                }
                $xfer += $input->readFieldEnd();
            }
            $xfer += $input->readStructEnd();
        } finally {
            $input->decrementRecursionDepth();
        }

        return $xfer;
    }

    public function write(TProtocol $output): int
    {
        $xfer = 0;
        $output->incrementRecursionDepth();
        try {
            $xfer += $output->writeStructBegin('SamplingStrategyResponse');
            if ($this->strategyType !== null) {
                $xfer += $output->writeFieldBegin('strategyType', TType::I32, 1);
                $xfer += $output->writeI32($this->strategyType);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->probabilisticSampling !== null) {
                if (!is_object($this->probabilisticSampling)) {
                    throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
                }
                $xfer += $output->writeFieldBegin('probabilisticSampling', TType::STRUCT, 2);
                $xfer += $this->probabilisticSampling->write($output);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->rateLimitingSampling !== null) {
                if (!is_object($this->rateLimitingSampling)) {
                    throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
                }
                $xfer += $output->writeFieldBegin('rateLimitingSampling', TType::STRUCT, 3);
                $xfer += $this->rateLimitingSampling->write($output);
                $xfer += $output->writeFieldEnd();
            }
            if ($this->operationSampling !== null) {
                if (!is_object($this->operationSampling)) {
                    throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
                }
                $xfer += $output->writeFieldBegin('operationSampling', TType::STRUCT, 4);
                $xfer += $this->operationSampling->write($output);
                $xfer += $output->writeFieldEnd();
            }
            $xfer += $output->writeFieldStop();
            $xfer += $output->writeStructEnd();
        } finally {
            $output->decrementRecursionDepth();
        }

        return $xfer;
    }
}
