<?php

/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 *
 * phpcs:disable PSR1.Methods.CamelCapsMethodName
 */

declare(strict_types=1);

namespace Jaeger\Thrift\Agent;

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class SamplingManagerClient implements \Jaeger\Thrift\Agent\SamplingManagerIf
{
    protected ?TProtocol $input = null;
    protected ?TProtocol $output = null;

    protected int $seqid = 0;

    public function __construct(TProtocol $input, ?TProtocol $output = null)
    {
        $this->input = $input;
        $this->output = $output ? $output : $input;
    }


    public function getSamplingStrategy(?string $serviceName): ?SamplingStrategyResponse
    {
        $this->send_getSamplingStrategy($serviceName);
        return $this->recv_getSamplingStrategy();
    }

    public function send_getSamplingStrategy(?string $serviceName): void
    {
        $args = new \Jaeger\Thrift\Agent\SamplingManager_getSamplingStrategy_args();
        $args->serviceName = $serviceName;
        $bin_accel = ($this->output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
        if ($bin_accel) {
            thrift_protocol_write_binary(
                $this->output,
                'getSamplingStrategy',
                TMessageType::CALL,
                $args,
                $this->seqid,
                $this->output->isStrictWrite()
            );
        } else {
            $this->output->writeMessageBegin('getSamplingStrategy', TMessageType::CALL, $this->seqid);
            $args->write($this->output);
            $this->output->writeMessageEnd();
            $this->output->getTransport()->flush();
        }
    }

    public function recv_getSamplingStrategy(): ?SamplingStrategyResponse
    {
        $bin_accel = ($this->input instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
        if ($bin_accel) {
            $result = thrift_protocol_read_binary(
                $this->input,
                '\Jaeger\Thrift\Agent\SamplingManager_getSamplingStrategy_result',
                $this->input->isStrictRead()
            );
        } else {
            $rseqid = 0;
            $fname = null;
            $mtype = 0;

            $this->input->readMessageBegin($fname, $mtype, $rseqid);
            if ($mtype == TMessageType::EXCEPTION) {
                $x = new TApplicationException();
                $x->read($this->input);
                $this->input->readMessageEnd();
                throw $x;
            }
            $result = new \Jaeger\Thrift\Agent\SamplingManager_getSamplingStrategy_result();
            $result->read($this->input);
            $this->input->readMessageEnd();
        }
        if ($result->success !== null) {
            return $result->success;
        }
        throw new \Exception("getSamplingStrategy failed: unknown result");
    }
}
